export const currencies = [
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "ILS", label: "ILS - Israeli New Shekel" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "KZT", label: "KZT - Kazakhstani Tenge" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "PLN", label: "PLN - Polish Złoty" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "TWD", label: "TWD - Taiwan Dollar" },
  { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
  { value: "USD", label: "USD - US Dollar" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "ZAR", label: "ZAR - South African Rand" },
];
