export const pricingPlans = [
  {
    name: "Free",
    price: "0",
    description: "Try our basic features",
    email: null,
    features: [
      "Up to 12 children",
      "Up to 10 parents",
      "1 staff member",
      "Basic attendance tracking",
      "Parent Web portal",
      "Activity tracking",
    ],
    cta: {
      text: "Get Started Free",
      href: "/register/free",
    },
    isPopular: false,
  },
  {
    name: "Basic",
    price: "29",
    description: "Perfect for small daycares",
    email: null,
    features: [
      "Up to 15 children",
      "Up to 15 parents",
      "Up to 2 staff members",
      "Basic attendance tracking",
      "Parent Web portal",
      "Parent Chat System",
      "Basic billing & payments",
      "Staff management",
      "Activity tracking",
      "Image Upload (5GB storage)",
      "Email notifications",
    ],
    cta: {
      text: "Start your 60-day free trial",
      href: "/register/basic",
    },
    isPopular: false,
  },
  {
    name: "Premium",
    price: "79",
    description: "For growing centers",
    email: null,
    features: [
      "Up to 30 children",
      "Up to 20 parents",
      "Up to 5 staff members",
      "Advanced attendance tracking",
      "Parent mobile app",
      "Parent Web portal",
      "Video chat system",
      "Full billing & payments",
      "Staff management",
      "Activity tracking",
      "Meal planning",
      "Health records",
      "Image & Video uploads (15GB total)",
      "Email & Push notifications",
    ],
    cta: {
      text: "Start your 30-day free trial",
      href: "/register/premium",
    },
    isPopular: true,
  },
  {
    name: "Enterprise",
    price: "",
    description: "For large organizations email us at ",
    email: "support@calivian.com",
    features: [
      "Unlimited children",
      "Unlimited parents",
      "Unlimited staff members",
      "Advanced attendance tracking",
      "Parent mobile app",
      "Parent Web portal",
      "Video chat system",
      "Full billing & payments",
      "Staff management",
      "Activity tracking",
      "Meal planning",
      "Health records",
      "Image & Video uploads (150GB total)",
      "Email, Push & SMS notifications",
      "API access",
      "Dedicated account manager",
    ],
    cta: {
      text: "support@calivian.com",
      href: "mailto:support@calivian.com",
    },
    isPopular: false,
  },
] as const;

export type PlanType = (typeof pricingPlans)[number]["name"];
